# Generated by Django 4.1.4 on 2023-02-13 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=7000)),
                ('ROI', models.IntegerField(default=0)),
                ('PNL', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollarValueAtPurchase', models.IntegerField(default=0)),
                ('dollarValueAtSale', models.IntegerField(blank=True, null=True)),
                ('coinAmount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('coinPurchased', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tradingplatform.cryptocoin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tradingplatform.platformuser')),
            ],
        ),
    ]
