# Generated by Django 4.1.4 on 2023-02-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingplatform', '0002_rename_dollarvalueatpurchase_position_dollarvalueofpurchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='coinAmount',
            field=models.FloatField(default=0),
        ),
    ]
