# Generated by Django 4.1.4 on 2023-02-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingplatform', '0003_alter_position_coinamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='dollarValueOfSale',
            new_name='USD_value_of_sale',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='coinAmount',
            new_name='coin_amount',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='coinPurchased',
            new_name='cryptocurrency',
        ),
        migrations.RemoveField(
            model_name='position',
            name='dollarValueOfPurchase',
        ),
        migrations.AddField(
            model_name='position',
            name='USD_value_of_purchase',
            field=models.IntegerField(default=0, verbose_name='Purchase Value'),
        ),
    ]
