# Generated by Django 4.1.4 on 2023-02-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingplatform', '0005_alter_platformuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='USD_value_of_purchase',
            field=models.PositiveIntegerField(default=0, verbose_name='Purchase Value'),
        ),
        migrations.AlterField(
            model_name='position',
            name='USD_value_of_sale',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
