# Generated by Django 4.1.4 on 2023-02-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingplatform', '0006_alter_position_usd_value_of_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='current_coin_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
