# Generated by Django 4.1.4 on 2023-02-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingplatform', '0007_position_current_coin_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='PNL',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='ROI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='PNL',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='ROI',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='current_coin_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
