# Generated by Django 4.1.4 on 2023-01-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTradeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('ROI', models.IntegerField()),
                ('PNL', models.IntegerField()),
                ('binance_users_following', models.IntegerField(verbose_name='IDs of followed Binance users')),
            ],
        ),
    ]
