# Generated by Django 4.1.4 on 2023-02-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_usertradedata_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTradeData',
        ),
    ]
